apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: vault-secrets-injector
  name: vault-secrets-injector-webhook-cfg
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: ${CA_BUNDLE}
    service:
      name: vault-secrets-injector-webhook-svc
      namespace: vault-secrets-injector
      path: /mutate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: grafana.vault-secrets-injector.rajshekhar17
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
    - pods
    - deployments
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10