apiVersion: v1
kind: Service
metadata:
  name: vault-secrets-injector-webhook-svc
  namespace: vault-secrets-injector
  labels:
    app: vault-secrets-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: vault-secrets-injector
