apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vault-secret-injector.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }} 
data:
  sidecarconfig.yaml: |
    containers:
    - name: sidecar-nginx
      image: nginx:1.12.2
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx
    volumes:
    - name: nginx-conf
      configMap:
        name: nginx-configmap
