apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "vault-secret-injector.fullname" . }}
  labels:
    app: vault-secrets-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-secrets-injector
  template:
    metadata:
      labels:
        app: vault-secrets-injector
    spec:
      serviceAccount: {{ include "vault-secret-injector.serviceAccountName" . }}
      containers:
        - name: {{ template "vault-secret-injector.fullname" . }}
          env:
            - name: VAULT_ADDR
              value: {{ .Values.vault.url }}
            - name: ROLE
              value: {{ .Values.vault.role }}
          image: rajshekhar17/vault-secret-injector:latest
          imagePullPolicy: Always
          args:
          - -sidecarCfgFile=/etc/webhook/config/sidecarconfig.yaml
          - -tlsCertFile=/etc/webhook/certs/tls.crt
          - -tlsKeyFile=/etc/webhook/certs/tls.key
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
          - name: webhook-config
            mountPath: /etc/webhook/config
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ template "vault-secret-injector.fullname" . }}-validation-webhook-keypair
      - name: webhook-config
        configMap:
          name: {{ template "vault-secret-injector.fullname" . }}-configmap
