{{- $cn := printf "%s.%s.svc" ( include "vault-secret-injector.service.validationWebhook" . ) .Release.Namespace }}
{{- $ca := genCA "vault-secret-injector-admission-ca" 3650 -}}
{{- $cert := genSignedCert $cn nil nil 3650 $ca -}}
kind: MutatingWebhookConfiguration
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
metadata:
  name: {{ template "vault-secret-injector.fullname" . }}-validations
  labels:
    {{- include "vault-secret-injector.metaLabels" . | nindent 4 }}
webhooks:
- name: validations.vault-secret-injector.vault-secret-injector
  matchPolicy: Equivalent
  namespaceSelector:
    matchLabels:
      {{- range $key, $val := .Values.webhook.namespaceLabels }}
      {{ $key }}: {{ $val }}
      {{- end }} 
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  sideEffects: None
  #{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  #admissionReviewVersions: ["v1"]
  #{{- else }}
  #admissionReviewVersions: ["v1beta1"]
  #{{- end }}
  admissionReviewVersions: ["v1beta1"]
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    {{- with .Values.webhook.resourcesToMutate }}
    resources:
      {{- toYaml . | nindent 4 }}
    {{- end }} 
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: {{ template "vault-secret-injector.service.validationWebhook" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault-secret-injector.service.validationWebhook" . }}
  labels:
    {{- include "vault-secret-injector.metaLabels" . | nindent 4 }}
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: vault-secrets-injector
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault-secret-injector.fullname" . }}-validation-webhook-keypair
  labels:
    {{- include "vault-secret-injector.metaLabels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}